[package]
name = "eip712"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "eip712"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
eip-712 = { path = "crates/EIP-712" }
serde_json = "1.0"
